package br.ucs.caxiaslixozero.Domain.Entities;

import java.util.Arrays;
import java.util.List;

public class Neighborhood {
    public static List<String> neighborhoodList = Arrays.asList(
        "Ana Rech",
        "Bela Vista",
        "Brandalise",
        "Centenário",
        "Centro",
        "Charqueadas",
        "Cidade Nova",
        "Cinquentenário",
        "Cristo Redentor",
        "Cruzeiro",
        "De Lazzer",
        "Desvio Rizzo",
        "Diamantino",
        "Esplanada",
        "Exposição",
        "Floresta",
        "Forqueta",
        "Galópolis",
        "Interlagos",
        "Jardelino Ramos",
        "Jardim América",
        "Jardim Eldorado",
        "Jardim das Hortências",
        "Kayser",
        "Madureira",
        "Maestra",
        "Mal Floriano",
        "Medianeira",
        "Monte Bérico",
        "N Sra da Saúde",
        "N Sra das Graças",
        "N Sra de Fátima",
        "N Sra de Lourdes",
        "N Sra do Rosário",
        "Panazzolo",
        "Parada Cristal",
        "Pedancino",
        "Petrópolis",
        "Pio X",
        "Pioneiro",
        "Planalto",
        "Por do Sol",
        "Presidente Vargas",
        "Reolon",
        "Rio Branco",
        "Sagrada Família",
        "Salgado Filho",
        "Samuara",
        "Santa Catarina",
        "Santa Corona",
        "Santa Fé",
        "Santa Justina",
        "Santo Antônio",
        "Sanvitto",
        "Serrano",
        "São Caetano",
        "São Ciro",
        "São Cristóvão",
        "São José",
        "São Leopoldo",
        "São Luiz da Sexta Légua",
        "São Pelegrino",
        "São Victor Cohab",
        "São Virgílio da Sexta Légua",
        "Universitário"
    );

}